const images = {
  courseImg: "/src/assets/img/courses/image.png",
  fileIcon: "/src/assets/img/courses/file.svg",
  accIcon: "/src/assets/img/courses/acc.svg",
  levelIcon: "/src/assets/img/courses/level.svg",
  avatarImg: "/src/assets/img/courses/ava.png",
  lineImg: "/src/assets/img/courses/line.svg"
};

const courses = [
  {
    img: images.courseImg,
    title: "Education Software and PHP and JS System Script",
    duration: "03 WEEKS",
    file: images.fileIcon,
    lessons: 8,
    acc: images.accIcon,
    students: "60+",
    lvl: images.levelIcon,
    level: "Beginner",
    ava: images.avatarImg,
    line: images.lineImg,
    author: "Max Alexix",
    rating: 4.7,
    cost: "$20",
  },
  {
    img: images.courseImg,
    title: "Learn Figma — UI/UX Design Essential Training",
    duration: "03 WEEKS",
    file: images.fileIcon,
    lessons: 8,
    acc: images.accIcon,
    students: "60+",
    lvl: images.levelIcon,
    level: "Beginner",
    ava: images.avatarImg,
    line: images.lineImg,
    author: "Max Alexix",
    rating: 4.7,
    cost: "$20",
  },
  {
    img: images.courseImg,
    title: "Learn Figma — UI/UX Design Essential Training",
    duration: "03 WEEKS",
    file: images.fileIcon,
    lessons: 8,
    acc: images.accIcon,
    students: "60+",
    lvl: images.levelIcon,
    level: "Beginner",
    ava: images.avatarImg,
    line: images.lineImg,
    author: "Max Alexix",
    rating: 4.7,
    cost: "$20",
  },
  {
    img: images.courseImg,
    title: "Learn Figma — UI/UX Design Essential Training",
    duration: "03 WEEKS",
    file: images.fileIcon,
    lessons: 8,
    acc: images.accIcon,
    students: "60+",
    lvl: images.levelIcon,
    level: "Beginner",
    ava: images.avatarImg,
    line: images.lineImg,
    author: "Max Alexix",
    rating: 4.7,
    cost: "$20",
  },
  {
    img: images.courseImg,
    title: "Learn Figma — UI/UX Design Essential Training",
    duration: "03 WEEKS",
    file: images.fileIcon,
    lessons: 8,
    acc: images.accIcon,
    students: "60+",
    lvl: images.levelIcon,
    level: "Beginner",
    ava: images.avatarImg,
    line: images.lineImg,
    author: "Max Alexix",
    rating: 4.7,
    cost: "$20",
  }

];

export default courses;
