const courses = [
    {
      img: '/src/assets/img/courses/image.png',
      title: "Education Software and PHP and JS System Script",
      duration: "03 WEEKS",
      file: '/src/assets/img/courses/file.svg',
      lessons: 8,
      acc: '/src/assets/img/courses/acc.svg',
      students: "60+",
      lvl: '/src/assets/img/courses/level.svg',
      level: "Beginner",
      ava: '/src/assets/img/courses/ava.png',
      line: '/src/assets/img/courses/line.svg',
      author: "Max Alexix",
      rating: 4.7,
      cost: "$500",
    },
    {
      img: '/src/assets/img/courses/image.png',
      title: "Learn Figma — UI/UX Design Essential Training",
      duration: "03 WEEKS",
      file: '/src/assets/img/courses/file.svg',
      lessons: 8,
      acc: '/src/assets/img/courses/acc.svg',
      students: "60+",
      lvl: '/src/assets/img/courses/level.svg',
      level: "Beginner",
      ava: '/src/assets/img/courses/ava.png',
      line: '/src/assets/img/courses/line.svg',
      author: "Max Alexix",
      rating: 4.7,
      cost: '$500',
    },
    {
        img: '/src/assets/img/courses/image.png',
        title: "Learn Figma — UI/UX Design Essential Training",
        duration: "03 WEEKS",
        file: '/src/assets/img/courses/file.svg',
        lessons: 8,
        acc: '/src/assets/img/courses/acc.svg',
        students: "60+",
        lvl: '/src/assets/img/courses/level.svg',
        level: "Beginner",
        ava: '/src/assets/img/courses/ava.png',
        line: '/src/assets/img/courses/line.svg',
        author: "Max Alexix",
        rating: 4.7,
        cost: '$500',
      },
      {
        img: '/src/assets/img/courses/image.png',
        title: "Advanced Android 12 & Kotlin Development Course",
        duration: "03 WEEKS",
        file: '/src/assets/img/courses/file.svg',
        lessons: 8,
        acc: '/src/assets/img/courses/acc.svg',
        students: "60+",
        lvl: '/src/assets/img/courses/level.svg',
        level: "Beginner",
        ava: '/src/assets/img/courses/ava.png',
        line: '/src/assets/img/courses/line.svg',
        author: "Max Alexix",
        rating: 4.7,
        cost: '$100',
      },
      {
        img: '/src/assets/img/courses/image.png',
        title: "IT Statistics Data Science and Business Analysis",
        duration: "03 WEEKS",
        file: '/src/assets/img/courses/file.svg',
        lessons: 8,
        acc: '/src/assets/img/courses/acc.svg',
        students: "60+",
        lvl: '/src/assets/img/courses/level.svg',
        level: "Beginner",
        ava: '/src/assets/img/courses/ava.png',
        line: '/src/assets/img/courses/line.svg',
        author: "Max Alexix",
        rating: 4.7,
        cost: 'FREE',
      },
  ];
  
  export default courses;