 const courses = [
  {
    img: "/src/assets/img/image.png",
    title: "Education Software and PHP and JS System Script",
    duration: "03 WEEKS",
    file: "/src/assets/img/file.svg",
    lessons: 8,
    acc: "/src/assets/img/acc.svg",
    students: "60+",
    lvl: "/src/assets/img/level.svg",
    level: "Beginner",
    ava: "/src/assets/img/ava.png",
    line: "/src/assets/img/line.svg",
    author: "Max Alexix",
    rating: 4.7,
    cost: "$20",
  },
  {
    img: "/src/assets/img/image.png",
    title: "Learn Figma — UI/UX Design Essential Training",
    duration: "03 WEEKS",
    file: "/src/assets/img/file.svg",
    lessons: 8,
    acc: "/src/assets/img/acc.svg",
    students: "60+",
    lvl: "/src/assets/img/level.svg",
    level: "Beginner",
    ava: "/src/assets/img/ava.png",
    line: "/src/assets/img/line.svg",
    author: "Max Alexix",
    rating: 4.7,
    cost: "$20",
  },
  {
    img: "/src/assets/img/image.png",
    title: "Education Software and PHP and JS System Script",
    duration: "03 WEEKS",
    file: "/src/assets/img/file.svg",
    lessons: 8,
    acc: "/src/assets/img/acc.svg",
    students: "60+",
    lvl: "/src/assets/img/level.svg",
    level: "Beginner",
    ava: "/src/assets/img/ava.png",
    line: "/src/assets/img/line.svg",
    author: "Max Alexix",
    rating: 4.7,
    cost: "$20",
  },
  {
    img: "/src/assets/img/image.png",
    title: "Learn Figma — UI/UX Design Essential Training",
    duration: "03 WEEKS",
    file: "/src/assets/img/file.svg",
    lessons: 8,
    acc: "/src/assets/img/acc.svg",
    students: "60+",
    lvl: "/src/assets/img/level.svg",
    level: "Beginner",
    ava: "/src/assets/img/ava.png",
    line: "/src/assets/img/line.svg",
    author: "Max Alexix",
    rating: 4.7,
    cost: "$20",
  },
  {
    img: "/src/assets/img/image.png",
    title: "Learn Figma — UI/UX Design Essential Training",
    duration: "03 WEEKS",
    file: "/src/assets/img/file.svg",
    lessons: 8,
    acc: "/src/assets/img/acc.svg",
    students: "60+",
    lvl: "/src/assets/img/level.svg",
    level: "Beginner",
    ava: "/src/assets/img/ava.png",
    line: "/src/assets/img/line.svg",
    author: "Max Alexix",
    rating: 4.7,
    cost: "$20",
  },

];

export default courses;
