import ava from '../../../assets/img/Courseslist/travis.jpg';
import img from '../../../assets/img/Courseslist/img.jpg';

const coursesData = [
  {
    id: 1,
    img: img,
    duration: '08 WEEKS',
    rating: 4.8,
    title: 'Education Software and PHP and JS System Script',
    lessons: 12,
    students: 120,
    level: 'Beginner',
    author: 'Max Aleksei',
    category: 'Development',
    price: 'Free',
    durationType: 'Short',
    instructor: 'Max Aleksei',
    desc: 'We are committed to making a positive impact on education globally. Through our initiatives, we strive to bridge educational gaps, improve learning outcomes.',
    ava: ava
  },
  {
    id: 2,
    img: img,
    duration: '06 WEEKS',
    rating: 4.7,
    title: 'Learn Figma – UI/UX Design Essential Training',
    lessons: 10,
    students: 90,
    level: 'Intermediate',
    author: 'Max Aleksei',
    category: 'Design',
    price: 'Free',
    durationType: 'Short',
    instructor: 'Max Aleksei',
    desc: 'We are committed to making a positive impact on education globally. Through our initiatives, we strive to bridge educational gaps, improve learning outcomes.',
    ava: ava
  },
  {
    id: 3,
    img: img,
    duration: '10 WEEKS',
    rating: 4.9,
    title: 'Advanced Android 12 & Kotlin Development Course',
    lessons: 15,
    students: 150,
    level: 'Advanced',
    author: 'Max Aleksei',
    category: 'Development',
    price: 'Free',
    durationType: 'Long',
    instructor: 'Max Aleksei',
    desc: 'We are committed to making a positive impact on education globally. Through our initiatives, we strive to bridge educational gaps, improve learning outcomes.',
    ava: ava
  },
  {
    id: 4,
    img: img,
    duration: '12 WEEKS',
    rating: 4.6,
    title: 'IT Statistics Data Science and Business Analysis',
    lessons: 18,
    students: 200,
    level: 'Intermediate',
    author: 'Max Aleksei',
    category: 'Data Science',
    price: 'Free',
    durationType: 'Long',
    instructor: 'Max Aleksei',
    desc: 'We are committed to making a positive impact on education globally. Through our initiatives, we strive to bridge educational gaps, improve learning outcomes.',
    ava: ava
  },
  {
    id: 5,
    img: img,
    duration: '08 WEEKS',
    rating: 4.5,
    title: 'The Complete HTML & CSS Bootcamp 2023 Edition',
    lessons: 14,
    students: 110,
    level: 'Beginner',
    author: 'Max Aleksei',
    category: 'Development',
    price: 'Free',
    durationType: 'Short',
    instructor: 'Max Aleksei',
    desc: 'We are committed to making a positive impact on education globally. Through our initiatives, we strive to bridge educational gaps, improve learning outcomes.',
    ava: ava
  },
  {
    id: 6,
    img: img,
    duration: '07 WEEKS',
    rating: 4.4,
    title: 'Fashion Photography From To Professional Course',
    lessons: 8,
    students: 80,
    level: 'Beginner',
    author: 'Max Aleksei',
    category: 'Photography',
    price: 'Free',
    durationType: 'Short',
    instructor: 'Max Aleksei',
    desc: 'We are committed to making a positive impact on education globally. Through our initiatives, we strive to bridge educational gaps, improve learning outcomes.',
    ava: ava
  },
  {
    id: 7,
    img: img,
    duration: '09 WEEKS',
    rating: 4.3,
    title: 'Python for Data Analysis and Visualization',
    lessons: 11,
    students: 95,
    level: 'Intermediate',
    author: 'Max Aleksei',
    category: 'Data Science',
    price: 'Free',
    durationType: 'Short',
    instructor: 'Max Aleksei',
    desc: 'We are committed to making a positive impact on education globally. Through our initiatives, we strive to bridge educational gaps, improve learning outcomes.',
    ava: ava
  }
];

export default coursesData;
